{
 "title": "Logs-2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "app",
    "label": "Aplication",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   { "name": "status", "label": "Status Code", "query": "201, 304, 400, 404, 500" },
   {
    "name": "level",
    "label": "Log Level",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {app=~\"$app\", namespace=~\"$namespace\"} \n        |= \"statusCode\"\n        | json\n        [${__range}]\n    )\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Success Requests 2xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {app=~\"$app\", namespace=~\"$namespace\"} \n        |= \"statusCode\"\n        | json\n        | res_statusCode < 400\n        [${__range}]\n    )\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Bad Requests 4xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {app=~\"$app\", namespace=~\"$namespace\"} \n        |= \"statusCode\"\n        | json\n        | res_statusCode >= 400 and res_statusCode < 500\n        [${__range}]\n    )\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Errored Requests 5xx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    count_over_time(\n        {app=~\"$app\", namespace=~\"$namespace\"} \n        |= \"statusCode\"\n        | json\n        | res_statusCode >= 500\n        [${__range}]\n    )\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count_over_time(\n    {app=~\"$app\", namespace=~\"$namespace\"} \n    |= \"statusCode\"\n    | json\n    | keep res_statusCode\n    [1m]\n)",
     "legendFormat": "{{res_statusCode}}"
    }
   ]
  },
  {
   "title": "App Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{level=~\"$level\"}\n| json \n| res_statusCode=~\"$status\"\n| line_format `{{ .msg }} {{ .app }} {{ .res_statusCode }} {{ .req_method }} {{ .req_url }} {{ .responseTime }}ms`"
    }
   ]
  }
 ]
}